Repository csrc-sdsu/mole, pull requests merged in 2025-01, with the labels that each got.

#40 Fix 'deprecated: use braced initialiser list instead' warning message
  src/cpp/divergence.cpp
  src/cpp/gradient.cpp
Labels: enhancement

#38 Sphinx setup initialization
  doc/sphinx/README.md
  doc/sphinx/requirements.txt
  doc/sphinx/source/api/cpp_api.rst
  doc/sphinx/source/api/introduction.rst
  doc/sphinx/source/api/matlab_api.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/index.rst
Labels: documentation

#45 Fix parabolic1D for Octave compatability
  examples/matlab/parabolic1D.m
Labels: bug

#51 Readme changes
  doc/sphinx/README.md
Labels: bug
