Repository csrc-sdsu/mole, pull requests merged in 2025-02, with the labels that each got.

#65 Fixed missing #include, and added doxygen content
  examples/cpp/Schrodinger2D.cpp
Labels: bug

#58 Latex pdf addition
  Makefile
  doc/sphinx/README.md
  doc/sphinx/requirements.txt
  doc/sphinx/source/_static/custom.sty
  doc/sphinx/source/api/CODE_OF_CONDUCT.rst
  doc/sphinx/source/api/CONTRIBUTING.rst
  doc/sphinx/source/api/cpp_api.rst
  doc/sphinx/source/api/gettingstarted.rst
  doc/sphinx/source/api/matlab_api.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/index.rst
Labels: documentation

#71 Google tests and Updated Github Actions
  .github/workflows/build_and_gtest.yml
  CMakeLists.txt
  src/cpp/utils.cpp
  tests/cpp/CMakeLists.txt
  tests/cpp/test1.cpp
  tests/cpp/test2.cpp
  tests/cpp/test3.cpp
  tests/cpp/test4.cpp
  tests/cpp/test5.cpp
Labels: Enhancement

#87 convection_diffusion3D | Name fix
  .gitignore
  examples/cpp/convection_diffusion3D.cpp
  examples/matlab/convection_diffusion3D.m
Labels: Enhancement, Bug

#90 Fixed openBlas issue in CmakeLists
  CMakeLists.txt
Labels: Bug

#92 MacOS + SuperLU build fix
  CMakeLists.txt
Labels: Enhancement, Refactoring, Bug
